# Generated by Django 5.1.4 on 2025-02-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tienda',
        ),
    ]
