# Generated by Django 5.1.4 on 2025-02-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd_PythonApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backEnd_PythonApp.tienda'),
        ),
    ]
